[package]
name = "field-assembly"
version = "0.1.0"
authors = ["jon-chuang <9093549+jon-chuang@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mince = { path = "../mince" }
paste = "0.1"
