[package]
name = "r1cs-std"
version = "0.1.0"
authors = [
    "Sean Bowe",
    "Alessandro Chiesa",
    "Matthew Green",
    "Ian Miers",
    "Pratyush Mishra",
    "Howard Wu",
    "Daniele Di Benedetto <daniele@horizenlabs.io>",
    "Marcelo Kaihara <marcelo@horizenlabs.io>",
    "Ulrich Haboeck <ulrich@horizenlabs.io>"
]
description = "A standard library for constraint system gadgets"
edition = "2018"
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"

################################# Dependencies ################################

[dependencies]
algebra = { git = "https://github.com/HorizenOfficial/ginger-lib", branch = "proof_size_optimization" }
r1cs-core = { git = "https://github.com/HorizenOfficial/ginger-lib", branch = "proof_size_optimization" }
derivative = "2.2.0"
radix_trie = "0.2.1"
rand = { version = "0.8.4" }

[features]
llvm_asm = ["algebra/llvm_asm"]

full = [ "bls12_377", "bn_382", "edwards_bls12", "edwards_sw6", "jubjub", "mnt4_753", "mnt6_753", "tweedle" ]

bls12_377 = [ "algebra/bls12_377" ]
bn_382 = [ "algebra/bn_382" ]
edwards_bls12 = [ "algebra/edwards_bls12"]
edwards_sw6 = [ "algebra/edwards_sw6", "algebra/sw6"]
jubjub = [ "algebra/jubjub" ]
mnt4_753 = [ "algebra/mnt4_753" ]
mnt6_753 = [ "algebra/mnt6_753" ]
tweedle = [ "algebra/tweedle" ]

[dev-dependencies]
rand_xorshift = { version = "0.3.0" }
algebra = { git = "https://github.com/HorizenOfficial/ginger-lib", branch = "proof_size_optimization", features = ["bls12_381", "jubjub"] }